### ISSUE TITLE
Unable to upgrade

### ISSUE THREAD

**Issue by elpekos** [twam/homebrew-openfpga#1]
==> Upgrading twam/openfpga/nextpnr --without-gui --without-arch-ecp5
==> Downloading https://github.com/YosysHQ/nextpnr/archive/c9ba65e7b2364147f8b27fbff1bb85a961f665c4.tar.gz
Already downloaded: /Users/tp/Library/Caches/Homebrew/downloads/43be845b3202b30561dc4606cb3e3b3f76305c16e7905ce55227dc822620147c--nextpnr-c9ba65e7b2364147f8b27fbff1bb85a961f665c4.tar.gz
==> cmake -DBUILD_GUI=OFF -DARCH=ice40 . -GNinja -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/nextpnr/20190518 -DCMAKE_BUILD_TYPE=Release -D
Last 15 lines from /Users/tp/Library/Logs/Homebrew/nextpnr/01.cmake:
CMake Error at CMakeLists.txt:192 (find_package):
  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/tmp/nextpnr-20190601-53218-jbv5wz/nextpnr-c9ba65e7b2364147f8b27fbff1bb85a961f665c4/CMakeFiles/CMakeOutput.log".

**Comment by twam** [comment]
Does it work if you install `eigen` first with `brew install eigen`?

**Comment by elpekos** [comment]
Hi,

Thanks a lot. I installed eigen and now upgrade worked.

Best regards,

T.

**Comment by twam** [comment]
Thanks for letting me know and testing. I added the dependency to nextpnr now.
